version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - task-service
      - notification-service
  
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"

  task-service:
    build: ./task-service
    ports:
      - "5002:5002"

  notification-service:
    build: ./notification-service
    ports:
      - "5003:5003"

  database:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: project_management

  redis-cache:
    image: redis:latest
